aa: rand-m7-mstd0.5-inc1
amp: true
aug_splits: 0
batch_size: 256
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint: ''
checkpoint_hist: 2
class_map: ''
classifier: seq2seq_l3_h8_512
clip_grad: null
clip_mode: norm
color_jitter: 0.3
cooldown_epochs: 0
crop_pct: null
ctc: false
cutmix: 0.0
cutmix_minmax: null
dataset_structure: separate
decay_epochs: 30
decay_rate: 0.1
decoder: null
dist_bn: ''
drop: 0.0
drop_block: null
drop_connect: null
drop_modules: null
drop_path: 0.15
epoch_repeats: 0.0
epochs: 250
eval_metric: SeqAcc
eval_plots_omit_most_occ: 0
gp: token
hflip: 0.0
input_size: 
- 3
- 160
- 352
img_size: null
initial_checkpoint: ''
initial_log: false
interpolation: ''
jsd: false
keep_unpacked: false
labels_subdir: ''
legacy_jit: false
local_rank: 0
log_interval: 50
lr: 0.001
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: deit3_base_patch16_224_in21ft1k
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
no_aug: false
no_prefetcher: false
no_resume_opt: false
no_test_pool: false
num_classes: null
opt: lamb
opt_betas: null
opt_eps: null
patience_epochs: 10
pin_mem: false
plots: null
predict_folders: null
predict_on_subfolders: false
pretrained: true
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: const
reprob: 0.0
resize_method: resize
resplit: false
resume: ''
return_individual_probs: false
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
seq2seq: true
skip_validate: false
smoothing: 0.1
split_bn: false
sqnet_version: v2
start_epoch: null
std: null
sync_bn: false
tf_preprocessing: false
tl_from_input_size: null
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_ema: false
use_multi_epochs_loader: false
val_split: validation
validation_batch_size_multiplier: 1
vflip: 0.0
wandb_project_prefix: ''
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.02
workers: 4
