aa: rand-m7-mstd0.5-inc1
amp: true
apex_amp: false
aug_splits: 0
batch_size: 256
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
clip_grad: 0.02
clip_mode: agc
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: 1.0
cutmix: 0.0
cutmix_minmax: null
decay_epochs: 1.0
decay_rate: 0.988
dist_bn: reduce
drop: 0.4
drop_block: null
drop_connect: null
drop_path: 0.25
epochs: 240
gp: fast
hflip: 0.0
input_size: 
- 3
- 160
- 352
jsd: false
local_rank: 0
lr: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: tf_efficientnetv2_s_in21k
model_ema: false
model_ema_decay: 0.999975
model_ema_force_cpu: false
momentum: 0.9
native_amp: true
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: null
opt: sgd
opt_betas: null
opt_eps: 0.001
pretrained: true
recount: 3
recovery_interval: 0
remode: pixel
reprob: 0.4
resize_method: Resize
resize_pad: null
resplit: false
save_images: false
sched: cosine
seed: 42
sequence_model: true
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size_multiplier: 1
vflip: 0.0
wandb_project_prefix: DARE-
warmup_epochs: 10
warmup_lr: 1.0e-06
weight_decay: 7.0e-06